anct-cnum/suite-gestionnaire-numerique

package.json, pnpm-lock.yaml
Permet de voir en une seule commande les dépendances qui ne sont plus utilisées.
=> :sparkles: Mise en place du package depcheck

.husky/pre-push, package.json, pnpm-lock.yaml
L'idée est que les linters et les tests soient lancés avant de pusher plutôt que sur la CI pour avoir un feedback plus rapide et moins consommer d'énergie sur une CI.
=> :sparkles: Mise en place de Husky et de son pre push

package.json
La licence AGPL 3 est celle utilisée par défaut dans les projets ANCT
=> :page_facing_up: Mise à jour de la license vers AGPL 3.0

seeds/departement.ts, seeds/groupement.ts, seeds/region.ts, seeds/structure.ts, seeds/utilisateur.ts
Vu que l'on a transformé les jeux de test en constante faisait que la fonction appelante ne les connaissait pas, il aurait fallu les mettre au dessus mais ce n'est pas dans nos conventions.
=> Les jeux de test pour la migration ont été remis en fonction

src/use-cases/queries/RechercherMesUtilisateurs.test.ts
Le fait d’implémenter à la main un Spy ne détecte pas quand on ajoute des paramètres à une fonction : le test est vert alors que l’implémentation de l’interface n’est pas bonne et rien ne me le dit sauf les tests de mutation…
=> Elimination de mutant dans la recherche de mes utilisateurs

custom.d.ts, package.json, prisma/migrations/20241029135940_ajout_de_champs_a_la_structure/migration.sql, prisma/migrations/20241030110516_ajout_de_champs_a_la_structure/migration.sql, prisma/schema.prisma, seeds/structure.ts, seeds/utilisateur.ts, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/domain/Structure.ts, src/gateways/PostgreMesInformationsPersonnellesLoader.test.ts, src/gateways/PostgreMesInformationsPersonnellesLoader.ts, src/gateways/PostgreUtilisateurLoader.test.ts, src/gateways/PostgreUtilisateurLoader.ts, src/gateways/PostgreUtilisateurRepository.test.ts, src/gateways/PostgreUtilisateurRepository.ts, src/gateways/shared/RoleMapper.ts, src/presenters/mesInformationsPersonnellesPresenter.ts, src/use-cases/queries/RecupererMesInformationsPersonnelles.ts, yarn.lock
Les champs migrés sont pour le filtre structure et pour enlever le bouchon qui restait dans mes informations personnelles.
La lib `prisma-json-types-generator` permet de typer les objets JSON.
=> Migration de champs pour une structure

src/components/shared/Pagination/Pagination.test.tsx, src/presenters/paginationPresenter.ts
On passe de 83 mutants à 40 ce qui réduit le temps d'exécution.
=> Simplification de la logique de la pagination pour réduire le nombre de mutant

src/components/shared/Drawer/Drawer.test.tsx, src/components/transverse/EnTete/EnTete.test.tsx
Pour éviter de tester sa fermeture dans les composants qui l'appelle.
=> Tester le drawer

src/app/api/actions/inviterUnUtilisateurAction.test.ts, src/app/api/actions/inviterUnUtilisateurAction.ts, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/shared/Drawer/Drawer.tsx, src/components/shared/Radio/Radio.tsx, src/components/shared/Radio/RadioGroup.tsx, src/components/shared/TextInput/TextInput.tsx, src/components/testHelper.tsx, src/domain/Role.ts, src/domain/Utilisateur.ts, src/domain/shared/Model.ts, src/gateways/PostgreUtilisateurLoader.test.ts, src/presenters/sessionUtilisateurPresenter.test.ts, src/presenters/sessionUtilisateurPresenter.ts, src/use-cases/commands/InviterUnUtilisateur.test.ts, src/use-cases/commands/InviterUnUtilisateur.ts, src/use-cases/queries/shared/UnUtilisateurReadModel.ts, src/use-cases/testHelper.ts
- ~[ ] écriture en base : insérer l'information sur l'organisation et gérer l'éventuelle erreur SQL en cas d'incohérence (FK)~ à faire suite au refacto du domaine
=> Suite de l'invitation

.eslintrc, src/app/api/actions/changerMonRoleAction.test.ts, src/app/api/actions/changerMonRoleAction.ts, src/app/api/actions/inviterUnUtilisateurAction.test.ts, src/app/api/actions/inviterUnUtilisateurAction.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.test.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.ts, src/app/api/actions/reinviterUnUtilisateurAction.test.ts, src/app/api/actions/reinviterUnUtilisateurAction.ts, src/app/api/actions/supprimerMonCompteAction.test.ts, src/app/api/actions/supprimerMonCompteAction.ts, src/app/api/actions/supprimerUnUtilisateurAction.test.ts, src/app/api/actions/supprimerUnUtilisateurAction.ts, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/ReinviterUnUtilisateur.tsx, src/components/MesUtilisateurs/SupprimerUnUtilisateur.tsx, src/components/shared/ClientContext.tsx, src/components/testHelper.tsx, src/components/transverse/EnTete/EnTete.test.tsx, src/components/transverse/EnTete/MenuUtilisateur/SelecteurRole/SelecteurRole.tsx
Proposition d'inversion de controler des server actions.
L'idée m'est venu grâce à la [documentation](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#passing-actions-as-props).
Cela permet de :
- retirer des spyOn et donc simplifier l'écriture de test
- notre context devient de plus en plus notre injecteur de dépendance
- réduire le couplage entre les controllers et les components
- surement améliorer le temps des mutations testing
=> Inversion de controle des server actions

.eslintrc, src/app/global-error.tsx, src/components/MesUtilisateurs/FiltrerParZonesGeographiques.tsx, src/components/MesUtilisateurs/OrganisationInput.tsx, src/components/shared/Modal/Modal.tsx, src/use-cases/CommandHandler.ts, src/use-cases/QueryHandler.ts, src/use-cases/commands/shared/EmailGateway.ts, src/use-cases/commands/shared/UtilisateurRepository.ts, src/use-cases/queries/RechercherLesStructures.ts, src/use-cases/queries/RechercherMesUtilisateurs.ts, src/use-cases/queries/RechercherUnUtilisateur.ts, src/use-cases/queries/RecupererMesInformationsPersonnelles.ts, src/use-cases/queries/RecupererUneGouvernance.ts
Comme expliqué ici : https://typescript-eslint.io/rules/method-signature-style/, on peut déclarer des méthodes de deux façons, avec la syntaxe _method shorthand_ ou la syntaxe propriété avec type de fonction.  
Dans notre base de code, on a tendance à préférer la première, par exemple :
```typescript
find(uid: UtilisateurUidState['value']): Promise<Utilisateur | null>
``` 
mais le _linter_ modifie le code dans les interfaces à la faveur de la seconde :
```typescript
find: (uid: UtilisateurUidState['value']) => Promise<Utilisateur | null>
```
L'objet de cette PR est d'uniformiser les déclarations sous la forme _method shorthand_.
~~- [ ] Relire le ticket~~
~~- [ ] Ajouter des variables d'environnement sur la production au besoin~~
~~- [ ] Vérifier l'accessibilité avec a11y.css~~
~~- [ ] …
=> style(méthodes): signatures sous forme de fonction, non de propriété

src/domain/Administrateur.ts, src/domain/GestionnaireDepartement.ts, src/domain/GestionnaireGroupement.ts, src/domain/GestionnaireRegion.ts, src/domain/GestionnaireStructure.ts, src/domain/Utilisateur.ts, src/domain/UtilisateurFactory.test.ts, src/domain/UtilisateurFactory.ts, src/domain/shared/Model.ts, src/gateways/PrismaUtilisateurLoader.ts, src/gateways/PrismaUtilisateurRepository.test.ts, src/gateways/PrismaUtilisateurRepository.ts, src/use-cases/commands/ChangerMonRole.test.ts, src/use-cases/commands/CorrigerNomPrenomSiAbsents.test.ts, src/use-cases/commands/InviterUnUtilisateur.test.ts, src/use-cases/commands/InviterUnUtilisateur.ts, src/use-cases/commands/MettreAJourUidALaPremiereConnexion.test.ts, src/use-cases/commands/ModifierMesInformationsPersonnelles.test.ts, src/use-cases/commands/ReinviterUnUtilisateur.test.ts, src/use-cases/commands/ReinviterUnUtilisateur.ts, src/use-cases/commands/SupprimerUnUtilisateur.test.ts
Je propose de faire de la méthode `state` de `Model` un [accesseur](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get). Concrètement, ce que ça change est que l'on appelle plus `model.state()` mais `model.state`, en vertu du [principe d'accès universel](https://martinfowler.com/bliki/UniformAccessPrinciple.html).
=> refactor(Model): la méthode state devient un accesseur

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/page.tsx, src/app/(connecte)/(sans-menu)/mes-informations-personnelles/page.tsx, src/app/(connecte)/(sans-menu)/mes-utilisateurs/page.tsx, src/app/(connecte)/layout.tsx, src/app/api/actions/changerMonRoleAction.ts, src/app/api/actions/inviterUnUtilisateurAction.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.ts, src/app/api/actions/reinviterUnUtilisateurAction.ts, src/app/api/actions/supprimerMonCompteAction.ts, src/app/api/actions/supprimerUnUtilisateurAction.ts, src/app/api/structures/route.ts, src/gateways/NextAuthAuthentificationGateway.ts, src/gateways/PrismaGouvernanceLoader.test.ts, src/gateways/PrismaGouvernanceLoader.ts, src/gateways/PrismaMesInformationsPersonnellesLoader.test.ts, src/gateways/PrismaMesInformationsPersonnellesLoader.ts, src/gateways/PrismaStructureLoader.test.ts, src/gateways/PrismaStructureLoader.ts, src/gateways/PrismaUtilisateurLoader.test.ts, src/gateways/PrismaUtilisateurLoader.ts, src/gateways/PrismaUtilisateurRepository.test.ts, src/gateways/PrismaUtilisateurRepository.ts
Cela permet de réduire la portée des resources auxquelles les gateways ont accès. Par exemple, un gateway de structures a besoin de la resource de données "structure", et ainsi ne doit pas pouvoir intéragir avec une resource de données "utilisateurs".
- ~~[ ] Relire le ticket~~
- ~~[ ] Naviguer au clavier~~
=> Gateways : remplacement des dépendances à PrismaClient par celles aux Prisma.XXXRecord

vitest.config.ts
Documentation de [environmentOptions](https://vitest.dev/config/#environmentmatchglobs)
- Duration 19.00s (transform 3.82s, setup 24.21s, collect 28.31s, tests 21.82s, environment 34.26s, prepare 6.81s)
- Duration 17.74s (transform 4.64s, setup 27.52s, collect 33.91s, tests 24.79s, environment 15.69s, prepare 7.95s)
- on gagne du coup 2 petites secs mais au moins, le jsdom n'est utilisé que pour les tests React
=> Changement de configuration dans vitest : environment par environmentMatchGlobs pour ne pas avoir jsdom pour les tests du back et gagner du temps

src/components/Connexion/Connexion.test.tsx, src/components/Gouvernance/Comitologie/Comitologie.test.tsx, src/components/Gouvernance/Comitologie/ComitologieRemplie.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRoute.test.tsx, src/components/Gouvernance/Gouvernance.test.tsx, src/components/Gouvernance/Membre/Membre.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesParametres/MesParametres.test.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.test.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/MesUtilisateurs/SupprimerUnUtilisateur.tsx, src/components/shared/Drawer/Drawer.module.css, src/components/shared/Pagination/DernierePage.tsx, src/components/testHelper.tsx, src/components/transverse/EnTete/EnTete.test.tsx
Ce qui a été fait et devient la norme :
- les tests deviennent des scénarii donc utilisation de petites fonctions faisant office d'action utilisateur commençant par `je + verbe` placé en bas du fichier
- ces fonctions d'actions utilisateur sont mise dans le `WHEN` pour mieux d'écrire les étapes
- ces même petits fonctions utilisent des petites fonctions techniques partagés dans testHelper
- la notion de render est aussi mise dans une petite fonction commençant par `afficherXXX`
- l'affichage du drawer est explicité par `toBeVisible` dorénavant avec une subtilité dans le `WHEN`
- on gagne 100 lignes !!!!
=> Simplification des tests en créant des petites fonctions helper

src/components/Gouvernance/NoteDeContexte/NoteDeContexte.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/MesUtilisateurs/ReinviterUnUtilisateur.tsx
Pour rappel, conceal n'est utile que dans le cas où il y a un message d'erreur qui doit s'afficher dans le formulaire sinon l'attribut aria-controls fait très bien l'affaire et ça évite de le doubler.
=> Suppression de conceal quand ce n'est pas nécessaire

prisma/migrations/20250130172026_ajout_des_types_aux_membres/migration.sql, prisma/schema.prisma, seeds/fne/schema.prisma, seeds/gouvernance.ts, src/gateways/PrismaGouvernanceLoader.test.ts, src/gateways/PrismaGouvernanceLoader.ts
=> Debouchonnement partiel membres

src/use-cases/commands/AjouterNoteDeContexteAGouvernance.test.ts, src/use-cases/commands/AjouterUnComite.test.ts, src/use-cases/commands/AjouterUneNotePrivee.test.ts, src/use-cases/commands/ModifierUnComite.test.ts, src/use-cases/commands/ModifierUneNoteDeContexte.test.ts, src/use-cases/commands/ModifierUneNotePrivee.test.ts, src/use-cases/commands/ReinviterUnUtilisateur.test.ts, src/use-cases/commands/SupprimerUnComite.test.ts, src/use-cases/commands/SupprimerUnUtilisateur.test.ts, src/use-cases/commands/SupprimerUneNotePrivee.test.ts
Dans la lignée de [simplifier les commands](https://github.com/anct-cnum/suite-gestionnaire-numerique/pull/349), il s'avère que certains expect devenaient inutile car ils sont redondant avec le test passant.
=> Suppression de certains expect inutiles dans les commands

src/components/FeuillesDeRoute/AjouterUneFeuilleDeRoute.test.tsx, src/components/FeuillesDeRoute/AjouterUneFeuilleDeRoute.tsx, src/components/FeuillesDeRoute/DetailAction.test.tsx, src/components/FeuillesDeRoute/ResumeAction.tsx, src/components/Gouvernance/Comitologie/Comitologie.test.tsx, src/components/Gouvernance/Comitologie/ComitologieRemplie.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRoute.test.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRouteRemplie.tsx, src/components/Gouvernance/Gouvernance.test.tsx, src/components/Gouvernance/Membre/Membre.test.tsx, src/components/Gouvernance/Membre/MembreRempli.tsx, src/components/Gouvernance/NoteDeContexte/NoteDeContexte.test.tsx, src/components/Gouvernance/NotePrivee/NotePrivee.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesMembres/MesMembres.test.tsx, src/components/MesMembres/MesMembres.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.test.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/transverse/EnTete/EnTete.test.tsx, src/components/transverse/EnTete/EnTete.tsx
Au final, je m'aperçois que personnalisé ce genre d'ID ne sert à rien et coute du temps quand on copie colle donc autant avoir tout le temps le même quand cela est possible.
=> Simplification du nommage autour des drawers

.eslintrc, src/components/Gouvernance/NoteDeContexte/ModifierNoteDeContexte.tsx, src/components/Gouvernance/NoteDeContexte/NoteDeContexte.test.tsx, src/components/shared/RichTextEditor/MenuBar.tsx, src/components/shared/RichTextEditor/MenuButton.tsx, src/components/shared/RichTextEditor/TextEditor.tsx, src/components/shared/RichTextEditor/hooks/useRichTextEditor.ts
- Plus besoin de doubler le textEditor, on écrit nos tests comme d'habitude et il faut insérer via `innerHTML` plutôt que `value` et ajouter un await juste après pour que cela fonctionne correctement
- Suppression de commentaire eslint inutile
- coverage augmenté
- ajout de la règle eslint pour interdire le vi.mock
=> Suppression du mock dans les tests du TextEditor

.vscode/typescriptreact.code-snippets, src/components/Action/Action.test.tsx, src/components/Action/AjouterDesBeneficiaires.test.tsx, src/components/Action/AjouterDesBesoins.test.tsx, src/components/Action/AjouterDesPorteurs.test.tsx, src/components/Connexion/Connexion.test.tsx, src/components/FeuilleDeRoute/ModifierUneFeuilleDeRoute.test.tsx, src/components/FeuillesDeRoute/AjouterUneFeuilleDeRoute.test.tsx, src/components/FeuillesDeRoute/DetailAction.test.tsx, src/components/GestionMembresGouvernance/AjouterUnMembre.test.tsx, src/components/Gouvernance/Comitologie/Comitologie.test.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRoute.test.tsx, src/components/Gouvernance/Gouvernance.test.tsx, src/components/Gouvernance/Membre/Membre.test.tsx, src/components/Gouvernance/NoteDeContexte/NoteDeContexte.test.tsx, src/components/Gouvernance/NotePrivee/NotePrivee.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.test.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/testHelper.tsx, src/components/transverse/EnTete/EnTete.test.tsx
Nous avions deux niveaux d'abstraction pour simplifier l'écriture des tests mais à l'utilisation, ça fait un de trop.
Donc suppression du niveau générique et plutôt mise en snippet pour les écrire rapidement au cas par cas selon les tests.
=> Suppression d'un niveau d'abstraction pour les fonctions helpers et plutôt mise en snippet

prisma/migrations/20250929085813_lien_membre_structure/migration.sql, prisma/migrations/20251001102002_ajout_categorie_juridique_structure/migration.sql, prisma/schema.prisma, src/app/api/actions/ajouterUnMembreAction.ts, src/components/GestionMembresGouvernance/AjouterUnMembrePage.tsx, src/components/shared/Membre/EntrepriseType.ts, src/domain/Membre.ts, src/domain/MembreCandidat.ts, src/domain/MembreConfirme.ts, src/domain/MembreFactory.ts, src/domain/Structure.ts, src/domain/UtilisateurFactory.ts, src/domain/testHelper.ts, src/gateways/PrismaMembreRepository.test.ts, src/gateways/PrismaMembreRepository.ts, src/gateways/PrismaStructureRepository.ts, src/presenters/entreprisePresenter.ts, src/use-cases/commands/AjouterUnMembre.test.ts, src/use-cases/commands/AjouterUnMembre.ts, src/use-cases/commands/DefinirUnCoPorteur.ts, src/use-cases/commands/RetirerUnCoPorteur.ts, src/use-cases/commands/shared/MembreRepository.ts, src/use-cases/commands/shared/StructureRepository.ts
Pour les nouveaux membre candidats créées, on va les lier à des strucutres de MIN. 
Cela permet d'avancer sur les gestionnaires de structure et d'avancer sur la notion de 'membre est une table d'asso gouvernance <=> structure)
Nous nous occupons pour l'instant pas des membres déjà créé.
=> 560 lier les membres à des structures de MIN
