package.json, pnpm-lock.yaml
Permet de détecter le code mort et d'autres truc inutile.
=> :sparkles: Mise en place du package knip

.gitignore, package.json, pnpm-lock.yaml
C'est pour tester nos composants React.
=> :sparkles: Mise en place du package React Testing Library

tsconfig.json
Configuration très stricte pour avoir un code robuste.
=> :sparkles: Configuration de TypeScript

next.config.mjs, package.json, pnpm-lock.yaml, vitest.config.ts
Comme ça c'est fait :)
J'en ai profité pour ajouter du typesafe pour les routes et mieux visualiser le code coverage pour la suite.
=> :sparkles: Mise en place du DSFR

next.config.mjs
Voici le constat https://securityheaders.com/?q=https%3A%2F%2Fsuite-gestionnaire.cleverapps.io%2F&followRedirects=on
On passera à A après cette PR
=> :sparkles: Amélioration de la sécurité dans les headers

package.json
[Documentation](https://eslint.org/docs/latest/use/command-line-interface#options)
=> :sparkles: Ajout d'un cache sur eslint pour gagner quelques secondes

src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesInformationsPersonnelles/supprimerMonCompteAction.ts, src/use-cases/commands/SupprimerMonCompte.ts
Self-awareness de la session côté serveur...
=> fix(supprimer mon compte): plus de transmission de l'email

tsconfig.json
Même si ça [fait autre chose à la base](https://www.typescriptlang.org/tsconfig/#noErrorTruncation), il aide aussi sur le typage.
=> Mise en place de la configuration TS noErrorTruncation pour améliorer la visibilité du typage quand on met sa souris dessus dans un IDE

src/app/(connecte)/layout.tsx, src/app/api/actions/inviterUnUtilisateurAction.test.ts, src/app/api/actions/inviterUnUtilisateurAction.ts, src/app/api/actions/supprimerMonCompteAction.ts, src/app/api/actions/supprimerUnUtilisateurAction.ts, src/gateways/PostgreMesInformationsPersonnellesLoader.test.ts, src/gateways/PostgreUtilisateurLoader.test.ts, src/gateways/PostgreUtilisateurRepository.ts, src/use-cases/commands/CorrigerNomPrenomSiAbsents.test.ts, src/use-cases/commands/CorrigerNomPrenomSiAbsents.ts, src/use-cases/commands/InviterUnUtilisateur.test.ts, src/use-cases/commands/InviterUnUtilisateur.ts, src/use-cases/commands/ModifierMesInformationsPersonnelles.test.ts, src/use-cases/commands/SupprimerUnUtilisateur.ts
Pour remettre les imports avec un `@` et sur la même ligne.
=> Uniformisation des imports

src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/SupprimerUnUtilisateur.tsx, src/components/shared/Modale/Modale.test.tsx, src/components/shared/Modale/Modale.tsx
Elle était déjà deux fois dans le code et ça permet aussi de rationnaliser des tests pour sa fermeture.
=> Création du composant Modale

src/app/api/actions/changerMonRoleAction.test.ts, src/app/api/actions/changerMonRoleAction.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.test.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.ts, src/app/api/actions/reinviterUnUtilisateurAction.test.ts, src/app/api/actions/reinviterUnUtilisateurAction.ts, src/app/api/actions/supprimerUnUtilisateurAction.test.ts, src/app/api/actions/supprimerUnUtilisateurAction.ts, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/ReinviterUnUtilisateur.tsx, src/components/MesUtilisateurs/SupprimerUnUtilisateur.tsx, src/components/shared/ClientContext.tsx, src/components/testHelper.tsx, src/components/transverse/EnTete/EnTete.test.tsx, src/components/transverse/EnTete/MenuUtilisateur/MenuUtilisateur.tsx, src/components/transverse/EnTete/MenuUtilisateur/SelecteurRole/SelecteurRole.tsx, src/shared/patterns.ts
Et uniformisation des servers actions
=> Suppression de window.location.reload quand c'est possible

.github/pull_request_template.md
=> Definition of done

src/components/MesUtilisateurs/FiltrerParZonesGeographiques.tsx, src/components/MesUtilisateurs/OrganisationInput.tsx, src/components/shared/ClientContext.tsx, src/domain/testHelper.ts, src/gateways/NextAuthAuthentificationGateway.ts, src/gateways/testHelper.ts, src/presenters/testHelper.ts, src/use-cases/testHelper.ts, stryker-backend.conf.json, stryker-frontend.conf.json
=> Ajout d'un commentaire stryker disable all dans les fichiers qui vont bien plutôt que dans la configuration pour que ça soit autoportant

.eslintrc, src/components/Gouvernance/Gouvernance.test.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/shared/Badge/Badge.module.css, src/components/shared/Badge/Badge.tsx, src/components/shared/Table/Table.tsx, src/gateways/PrismaGouvernanceLoader.test.ts, src/gateways/PrismaGouvernanceLoader.ts, src/presenters/mesUtilisateursPresenter.ts, src/presenters/shared/date.ts, src/use-cases/queries/RecupererUneGouvernance.ts
=> Mise en place d'une gouvernance remplie avec des données bouchonnées côté back #166

src/app/(connecte)/layout.tsx, src/use-cases/commands/ChangerMonRole.test.ts, src/use-cases/commands/CorrigerNomPrenomSiAbsents.test.ts, src/use-cases/commands/InviterUnUtilisateur.test.ts, src/use-cases/commands/MettreAJourUidALaPremiereConnexion.test.ts, src/use-cases/commands/ReinviterUnUtilisateur.test.ts, src/use-cases/commands/SupprimerUnUtilisateur.test.ts
=> les 'let' n'ont plus besoin d'être initialisés

src/app/(connecte)/(avec-menu)/gouvernance-vide/[codeDepartement]/page.tsx, src/components/Gouvernance/FeuilleDeRoute/ResumeFeuilleDeRoute.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/OrganisationInput.tsx, src/components/shared/Checkbox/Checkbox.tsx, src/components/shared/Table/Table.tsx, src/components/transverse/MenuLateral/MenuLateral.test.tsx, src/presenters/gouvernancePresenter.ts
+ élimination de quelques mutants et amélioration du coverage :)
=> Améliorer les tests avec react select event

src/app/(connecte)/(sans-menu)/mes-utilisateurs/page.tsx, src/app/api/structures/route.test.ts, src/app/api/structures/route.ts, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.tsx, src/components/MesUtilisateurs/FiltrerParZonesGeographiques.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/OrganisationInput.tsx, src/components/testHelper.tsx, src/gateways/PrismaStructureLoader.test.ts, src/gateways/PrismaStructureLoader.ts, src/gateways/PrismaUtilisateurLoader.test.ts, src/gateways/PrismaUtilisateurLoader.ts, src/presenters/filtresUtilisateurPresenter.ts, src/presenters/zonesGeographiquesPresenter.ts, src/shared/lang.ts, src/use-cases/queries/RechercherLesStructures.ts, src/use-cases/queries/RechercherMesUtilisateurs.ts
=> feat(filtrage): recherche d'utilsateurs pas appartenance à une structure

src/components/Gouvernance/Comitologie/ComitologieRemplie.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRouteRemplie.tsx, src/components/Gouvernance/Membre/MembreRempli.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/shared/Radio/RadioGroup.tsx, src/components/shared/Statut/Statut.tsx, src/components/shared/Table/Table.tsx, src/components/shared/TextInput/TextInput.tsx, src/components/transverse/MenuLateral/MenuLateral.test.tsx, src/components/transverse/MenuLateral/MenuLateral.tsx, src/gateways/PrismaUtilisateurLoader.test.ts, src/gateways/PrismaUtilisateurLoader.ts, src/presenters/mesUtilisateursPresenter.ts, src/presenters/sessionUtilisateurPresenter.test.ts, src/presenters/sessionUtilisateurPresenter.ts, src/presenters/testHelper.ts, src/use-cases/queries/shared/UnUtilisateurReadModel.ts, src/use-cases/testHelper.ts
On est passé de 926 mutants à 905 mutants !
- ~~[ ] Relire le ticket~~
=> Supprimer des if quand possible

src/components/Gouvernance/Comitologie/AjouterUnComite.tsx, src/components/Gouvernance/Comitologie/Comitologie.test.tsx, src/components/Gouvernance/Comitologie/ComitologieRemplie.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/shared/SegmentedControl/SegmentedControl.tsx, src/components/shared/TextInput/TextInput.tsx, src/components/transverse/EnTete/EnTete.test.tsx, src/components/transverse/EnTete/EnTete.tsx
=> Petites améliorations d'accessibilité

src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx
=> Réinitialisation des données dans le formulaire de modification de mes informations personnelles

package.json, src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/page.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/MesUtilisateurs/FiltrerParZonesGeographiques.tsx, src/components/shared/Drawer/Drawer.tsx, yarn.lock
[React 19](https://react.dev/blog/2024/12/05/react-19), les changements :
- Suppression de `forwardRef` devenu inutile
- Les title peuvent être mis à l’intérieur d’un composant
=> Mise à jour de React 19

src/components/Gouvernance/Gouvernance.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, vitest.setup.ts
En soit, il fallu juste rajouter le reset et tout le reste est du refactoring pour simplifier les tests.
=> Le bouton annuler réinitialise le champ de saisi e-mail dans le modale de suppression de mon compte

src/components/transverse/MenuLateral/MenuLateral.test.tsx, src/components/transverse/MenuLateral/MenuLateral.tsx
(Simple correction de l'orthographe )
- ~~[ ] Recetter l'application~~
- ~~[ ] Regarder le commentaire de sonarcloud et corriger s'il est pertinent~~
- ~~[ ] Naviguer au clavier~~
- ~~[ ] Lancer les tests de mutation~~
=> Retour : Menu Latéral Gestionnaire Département

src/components/Gouvernance/Comitologie/AjouterUnComite.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/shared/SubmitButton/SubmitButton.tsx, src/global.css
=> Tous les boutons submit sont désactivés et changent de wording quand on clique dessus puis se réactivent quand l'action est finie

src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/global.css
=> Clique sur filtrer

src/app/(connecte)/(sans-menu)/mes-utilisateurs/page.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.test.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/OrganisationInput.tsx, src/components/testHelper.tsx, src/presenters/mesUtilisateursPresenter.ts
=> Ajout du placeholder 'Nom de la structure' sur le filtre 'Par structure' dans les filtres de mes utilisateurs #91

src/app/api/structures/route.test.ts, src/app/api/structures/route.ts, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.test.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/OrganisationInput.tsx, src/components/testHelper.tsx, src/gateways/PrismaStructureLoader.test.ts, src/gateways/PrismaStructureLoader.ts, src/gateways/PrismaUtilisateurLoader.test.ts, src/gateways/PrismaUtilisateurLoader.ts, src/presenters/rechercheStructuresPresenter.ts, src/use-cases/queries/RechercherLesStructures.test.ts, src/use-cases/queries/RechercherLesStructures.ts
=> feat(filtrage par structures): affichage du nom de la commune

src/app/(connecte)/(sans-menu)/mes-informations-personnelles/page.tsx, src/app/(connecte)/(sans-menu)/mes-utilisateurs/page.tsx, src/app/api/actions/changerMonRoleAction.test.ts, src/app/api/actions/changerMonRoleAction.ts, src/app/api/actions/inviterUnUtilisateurAction.test.ts, src/app/api/actions/inviterUnUtilisateurAction.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.test.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.ts, src/app/api/actions/reinviterUnUtilisateurAction.test.ts, src/app/api/actions/reinviterUnUtilisateurAction.ts, src/app/api/actions/supprimerMonCompteAction.test.ts, src/app/api/actions/supprimerMonCompteAction.ts, src/app/api/actions/supprimerUnUtilisateurAction.test.ts, src/app/api/actions/supprimerUnUtilisateurAction.ts, src/gateways/NextAuthAuthentificationGateway.ts
Afin d'éviter que ça n'évoque une éventuelle notion de "sous session".
- ~~[ ] Relire le ticket~~
- ~~[ ] Vérifier l'accessibilité avec a11y.css, WAVE, Axe, headingMap~~
- ~~[ ] Naviguer au clavier~~
- ~~[ ] Lancer les tests de mutation~~
=> refactor: renommage de getSubSession en getSessionSub

src/components/Gouvernance/FeuilleDeRoute/ResumeFeuilleDeRoute.tsx, src/components/Gouvernance/Gouvernance.module.css, src/components/Gouvernance/Membre/ResumeMembre.tsx, src/components/Gouvernance/NoteDeContexte/ResumeNoteDeContexte.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/shared/Drawer/Drawer.module.css, src/components/shared/Table/Table.module.css, src/components/transverse/EnTete/EnTete.module.css, src/components/transverse/EnTete/EnTete.tsx, src/components/transverse/EnTete/MenuUtilisateur/MenuUtilisateur.tsx, src/global.css
=> Correction de retour de design

src/domain/Administrateur.ts, src/domain/Comite.ts, src/domain/GestionnaireDepartement.ts, src/domain/GestionnaireGroupement.ts, src/domain/GestionnaireRegion.ts, src/domain/GestionnaireStructure.ts, src/domain/Gouvernance.ts, src/domain/Utilisateur.ts, src/domain/testHelper.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.test.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.ts, src/use-cases/commands/AjouterUnComite.test.ts, src/use-cases/commands/AjouterUnComite.ts, src/use-cases/commands/shared/ComiteRepository.ts
=> Ajout du département à la gouvernance et l'uid d'un gouvernance à un comité

src/components/Gouvernance/Comitologie/AjouterUnComite.tsx, src/components/Gouvernance/FeuilleDeRoute/DetailsFeuilleDeRoute.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRouteRemplie.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/Gouvernance/Membre/Membre.tsx, src/components/Gouvernance/Membre/MembreRempli.tsx, src/components/shared/Drawer/Drawer.tsx
David a remonté un problème de scroll sur le drawer que j'avais réglé de la mauvaise manière il y a quelques jours donc là c'est mieux en ayant changé l'architecture du drawer au niveau du titre.
=> Réglage du scroll vertical sur le drawer

src/domain/Gouvernance.test.ts, src/domain/Gouvernance.ts, src/domain/testHelper.ts, src/gateways/PrismaGouvernanceRepository.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.ts, src/use-cases/commands/AjouterUnComite.test.ts, src/use-cases/commands/AjouterUnComite.ts, src/use-cases/commands/ModifierMesInformationsPersonnelles.test.ts
Je me suis permis d'enlever aussi la notion utilisateur qui ne servait à rien !
=> seuls les gestionnaires de région ayant le même département que la gouvernance peuvent la gérer

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/page.tsx, src/gateways/PrismaGouvernanceLoader.test.ts, src/gateways/PrismaGouvernanceLoader.ts
=> Gateways:  Visualiser le détail d'un membre de la gouvernance

src/components/Gouvernance/Comitologie/AjouterUnComite.tsx, src/components/Gouvernance/Comitologie/ModifierUnComite.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/shared/Search/Search.tsx, src/components/shared/SubmitButton/SubmitButton.tsx
=> Le composant SubmitButton a un children plutôt qu'un prop

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/page.tsx, src/components/Gouvernance/Gouvernance.test.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/Gouvernance/Membre/Membre.test.tsx, src/components/Gouvernance/Membre/Membre.tsx, src/components/Gouvernance/Membre/MembreRempli.tsx, src/presenters/gouvernancePresenter.ts, src/use-cases/queries/RecupererUneGouvernance.test.ts, src/use-cases/queries/RecupererUneGouvernance.ts, src/use-cases/testHelper.ts
=> Web: Visualiser le détail d'un membre de la gouvernance

src/app/api/actions/supprimerUnComiteAction.test.ts, src/app/api/actions/supprimerUnComiteAction.ts, src/components/Gouvernance/Comitologie/Comitologie.test.tsx, src/components/Gouvernance/Comitologie/ModifierUnComite.tsx, src/components/Gouvernance/Gouvernance.module.css, src/components/shared/ClientContext.tsx, src/components/shared/Notification/Notification.tsx, src/components/shared/RichTextEditor/MenuBar.tsx, src/components/shared/RichTextEditor/MenuButton.tsx, src/components/shared/RichTextEditor/TextEditor.tsx, src/components/shared/TextArea/TextArea.tsx, src/components/testHelper.tsx, src/gateways/PrismaComiteRepository.test.ts, src/gateways/PrismaComiteRepository.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.test.ts, src/use-cases/commands/AjouterUnComite.test.ts, src/use-cases/commands/ModifierUnComite.test.ts, src/use-cases/commands/SupprimerUnComite.test.ts, src/use-cases/commands/SupprimerUnComite.ts, src/use-cases/commands/shared/ComiteRepository.ts
=> Supprimer comite

src/domain/Comite.ts, src/domain/Gouvernance.test.ts, src/domain/Gouvernance.ts, src/domain/testHelper.ts, src/gateways/PrismaComiteRepository.test.ts, src/gateways/PrismaComiteRepository.ts, src/gateways/PrismaGouvernanceRepository.ts, src/use-cases/commands/AjouterUnComite.test.ts, src/use-cases/commands/AjouterUnComite.ts, src/use-cases/commands/AjouterUneNotePrivee.test.ts, src/use-cases/commands/AjouterUneNotePrivee.ts, src/use-cases/commands/ModifierUnComite.test.ts, src/use-cases/commands/ModifierUnComite.ts, src/use-cases/commands/SupprimerUnComite.test.ts
=> Ajouter une note privée use case

src/app/api/actions/ajouterUnComiteAction.test.ts, src/app/api/actions/ajouterUnComiteAction.ts, src/app/api/actions/ajouterUneNoteDeContexteAction.test.ts, src/app/api/actions/ajouterUneNoteDeContexteAction.ts, src/app/api/actions/modifierUnComiteAction.test.ts, src/app/api/actions/modifierUnComiteAction.ts, src/app/api/actions/supprimerUnComiteAction.test.ts, src/app/api/actions/supprimerUnComiteAction.ts, src/domain/Comite.ts, src/domain/Gouvernance.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.test.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.ts, src/use-cases/commands/AjouterUnComite.test.ts, src/use-cases/commands/AjouterUnComite.ts, src/use-cases/commands/ModifierUnComite.test.ts, src/use-cases/commands/ModifierUnComite.ts, src/use-cases/commands/ModifierUneNotePrivee.test.ts, src/use-cases/commands/ModifierUneNotePrivee.ts, src/use-cases/commands/SupprimerUnComite.test.ts, src/use-cases/commands/SupprimerUnComite.ts
=> Modifier note privee use case

src/domain/GestionnaireDepartement.ts, src/domain/GestionnaireGroupement.ts, src/domain/GestionnaireRegion.ts, src/domain/GestionnaireStructure.ts, src/domain/Utilisateur.ts, src/domain/UtilisateurFactory.ts, src/use-cases/commands/InviterUnUtilisateur.test.ts, src/use-cases/commands/MettreAJourUidALaPremiereConnexion.test.ts, src/use-cases/commands/ReinviterUnUtilisateur.test.ts
=> fix(réinvitation): l'utilisateur réinvité doit être inactif

.eslintrc, src/domain/Administrateur.ts, src/domain/GestionnaireDepartement.ts, src/domain/GestionnaireGroupement.ts, src/domain/GestionnaireRegion.ts, src/domain/GestionnaireStructure.ts, src/domain/Utilisateur.ts
=> Simplification de la méthode isAdmin

prisma/migrations/20250130074134_ajout_table_feuille_de_route/migration.sql, prisma/schema.prisma, seeds/fne/schema.prisma, seeds/gouvernance.ts
=> chore(FNE): import des données feuilles de route

src/app/api/actions/supprimerUneNotePriveeAction.test.ts, src/app/api/actions/supprimerUneNotePriveeAction.ts, src/components/Gouvernance/NotePrivee/ModifierUneNotePrivee.tsx, src/components/Gouvernance/NotePrivee/NotePrivee.test.tsx, src/components/shared/ClientContext.tsx, src/components/testHelper.tsx, src/domain/Gouvernance.ts, src/gateways/PrismaGouvernanceRepository.test.ts, src/gateways/PrismaGouvernanceRepository.ts, src/use-cases/commands/SupprimerUneNotePrivee.test.ts, src/use-cases/commands/SupprimerUneNotePrivee.ts
=> Supprimer une note privée

.eslintrc, src/components/Connexion/Connexion.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/shared/RichTextEditor/MenuBar.tsx, src/components/shared/RichTextEditor/TextEditor.tsx, src/components/shared/RichTextEditor/hooks/useRichTextEditor.ts
=> Mini refacto

src/app/api/actions/modifierMesInformationsPersonnellesAction.test.ts, src/app/api/actions/modifierMesInformationsPersonnellesAction.ts, src/app/api/actions/reinviterUnUtilisateurAction.test.ts, src/app/api/actions/reinviterUnUtilisateurAction.ts
Il reste encore 3 server actions à simplifier mais il faut déplacer leur test côté use case, on verra plus tard.
=> Suppression de validation inutiles dans des server actions

src/components/Gouvernance/Comitologie/ComitologieRemplie.tsx, src/components/Gouvernance/FeuilleDeRoute/FeuilleDeRouteRemplie.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/Gouvernance/Membre/Membre.test.tsx, src/components/Gouvernance/Membre/MembreRempli.tsx, src/components/Gouvernance/NoteDeContexte/AjouterNoteDeContexte.tsx, src/components/Gouvernance/NoteDeContexte/NoteDeContexte.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/MesUtilisateurs/SupprimerUnUtilisateur.tsx, src/components/transverse/EnTete/EnTete.tsx
https://react.dev/reference/react/useId#generating-unique-ids-for-accessibility-attributes
"However, hardcoding IDs like this is not a good practice in React. A component may be rendered more than once on the page—but IDs have to be unique! Instead of hardcoding an ID, generate a unique ID with useId:"
=> utilisation de uesId()

src/components/Gouvernance/Comitologie/AjouterUnComite.tsx, src/components/Gouvernance/Comitologie/Comitologie.test.tsx, src/components/Gouvernance/Comitologie/ModifierUnComite.tsx, src/components/Gouvernance/NoteDeContexte/AjouterNoteDeContexte.tsx, src/components/Gouvernance/NoteDeContexte/ModifierNoteDeContexte.tsx, src/components/Gouvernance/NoteDeContexte/NoteDeContexte.test.tsx, src/components/Gouvernance/NotePrivee/AjouterUneNotePrivee.tsx, src/components/Gouvernance/NotePrivee/ModifierUneNotePrivee.tsx, src/components/Gouvernance/NotePrivee/NotePrivee.test.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.test.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/MesUtilisateurs/ReinviterUnUtilisateur.tsx, src/components/MesUtilisateurs/SupprimerUnUtilisateur.tsx
=> Une notification pour toutes les actions

.eslintrc, src/domain/Comite.ts, src/domain/Gouvernance.test.ts, src/domain/Gouvernance.ts, src/domain/Membre.ts, src/domain/MembreConfirme.ts, src/domain/MembreFactory.ts, src/domain/MembrePotentiel.ts, src/domain/shared/Exception.ts, src/domain/testHelper.ts, src/gateways/PrismaMesMembresLoader.test.ts, src/gateways/PrismaMesMembresLoader.ts, src/presenters/mesMembresPresenter.ts, src/presenters/testHelper.ts, src/use-cases/commands/AccepterUnMembre.test.ts, src/use-cases/commands/AccepterUnMembre.ts, src/use-cases/commands/AjouterNoteDeContexteAGouvernance.ts, src/use-cases/commands/AjouterUnComite.ts, src/use-cases/commands/AjouterUneNotePrivee.ts, src/use-cases/commands/ModifierUnComite.ts, src/use-cases/commands/ModifierUneNoteDeContexte.ts, src/use-cases/commands/ModifierUneNotePrivee.ts, src/use-cases/commands/SupprimerUnComite.ts, src/use-cases/commands/SupprimerUneNotePrivee.ts, src/use-cases/commands/shared/MembreRepository.ts, src/use-cases/queries/RecupererMesMembres.test.ts, src/use-cases/queries/RecupererMesMembres.ts, src/use-cases/testHelper.ts
=> Accepter un membre use case

src/gateways/PrismaGouvernanceLoader.ts, src/use-cases/queries/RecupererLesFeuillesDeRoute.test.ts, src/use-cases/queries/RecupererLesFeuillesDeRoute.ts, src/use-cases/queries/RecupererUneGouvernance.test.ts, src/use-cases/queries/RecupererUneGouvernance.ts, src/use-cases/testHelper.ts
=> Feuilles de route query

src/gateways/PrismaComiteRepository.test.ts, src/gateways/PrismaLesFeuillesDeRouteLoader.test.ts, src/gateways/PrismaLesFeuillesDeRouteLoader.ts, src/gateways/PrismaMesInformationsPersonnellesLoader.ts, src/gateways/PrismaUtilisateurRepository.test.ts
=> Feuilles de route loader

src/domain/Membre.ts, src/domain/MembreConfirme.ts, src/domain/MembreFactory.ts, src/domain/MembrePotentiel.ts, src/domain/testHelper.ts, src/gateways/PrismaGouvernanceRepository.test.ts, src/gateways/PrismaMembreRepository.test.ts, src/gateways/PrismaMembreRepository.ts, src/gateways/testHelper.ts, src/use-cases/commands/shared/MembreRepository.ts
=> Accepter un membre repository

prisma/migrations/20250213065426_contact_membres_gouvernance/migration.sql, prisma/schema.prisma, seeds/fne/schema.prisma, seeds/gouvernance.ts, src/gateways/PrismaMembreRepository.test.ts
=> chore(FNE): récupération des membres de gouvernance candidats et suggérés ainsi que des contacts des membres

src/app/layout.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/shared/RichTextEditor/TextEditor.tsx, src/components/transverse/EnTete/MenuUtilisateur/MenuUtilisateur.tsx
=> Correction de l'exception GouvernanceLoader

stryker-backend.conf.json, stryker-frontend.conf.json
=> Affichage du degré de complétion des tests de mutation

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/feuille-de-route/[uidFeuilleDeRoute]/page.tsx, src/components/FeuilleDeRoute/FeuilleDeRoute.test.tsx, src/components/FeuilleDeRoute/FeuilleDeRoute.tsx, src/components/FeuillesDeRoute/FeuillesDeRoute.test.tsx, src/components/FeuillesDeRoute/ResumeFeuilleDeRoute.tsx, src/presenters/feuilleDeRoutePresenter.ts, src/presenters/feuillesDeRoutePresenter.ts
=> feat(gouvernance): haut de page détail d'une feuille de route

.eslintrc, src/components/Action/Action.module.css, src/components/Action/AjouterDesBesoins.test.tsx, src/components/Action/AjouterDesBesoins.tsx, src/components/Action/AjouterUneAction.tsx, src/components/Action/FormulaireAction.tsx, src/components/Action/ModifierUneAction.tsx, src/components/FeuillesDeRoute/ResumeAction.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/Gouvernance/NoteDeContexte/AjouterNoteDeContexte.tsx, src/components/Gouvernance/NoteDeContexte/ModifierNoteDeContexte.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesInformationsPersonnelles/ModifierMonCompte.tsx, src/components/MesUtilisateurs/FiltrerParRoles.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/testHelper.tsx, src/presenters/actionPresenter.ts, src/presenters/feuillesDeRoutePresenter.ts, src/presenters/sessionUtilisateurPresenter.test.ts, src/presenters/shared/action.ts, src/presenters/testHelper.ts
- Les presenters ne doivent pas s'appeler entre eux donc rajout d'une règle eslint pour éviter ça
- enlever quelques ref sur les drawer qui ne servaient à rien
- simplification de certains fieldset qui avaient des info inutiles
=> Ajouter des besoins UI

prisma/migrations/20250226135210_membres_contacts_deviennent_requis/migration.sql, prisma/schema.prisma, seeds/gouvernance.ts, src/components/GestionMembresGouvernance/AjouterUnMembre.test.tsx, src/gateways/PrismaGouvernanceLoader.test.ts, src/gateways/PrismaGouvernanceLoader.ts, src/gateways/PrismaMembreRepository.test.ts, src/gateways/PrismaMesMembresLoader.test.ts, src/gateways/PrismaMesMembresLoader.ts, src/gateways/shared/MembresGouvernance.ts, src/gateways/testHelper.ts, src/presenters/membresPresenter.ts, src/use-cases/queries/RecupererMesMembres.test.ts, src/use-cases/queries/RecupererMesMembres.ts, src/use-cases/testHelper.ts
=> Correction membres

.eslintrc, src/components/Action/Action.module.css, src/components/Action/Action.test.tsx, src/components/Action/AjouterDesBeneficiaires.test.tsx, src/components/Action/AjouterDesBesoins.test.tsx, src/components/Action/AjouterDesBesoins.tsx, src/components/Action/AjouterDesMembres.tsx, src/components/Action/AjouterDesPorteurs.test.tsx, src/components/Action/FormulaireAction.tsx, src/components/FeuilleDeRoute/ModifierUneFeuilleDeRoute.test.tsx, src/components/shared/Checkbox/Checkbox.tsx, src/gateways/NextAuthAuthentificationGateway.ts, src/gateways/NodemailerEmailInvitationGateway.ts, src/presenters/actionPresenter.ts, src/presenters/sessionUtilisateurPresenter.test.ts, src/presenters/testHelper.ts, src/use-cases/testHelper.ts, vitest.setup.ts
- J'ai fait aussi l'ajout des bénéficiaires qui est identique.
- Amélioration de règle d'import pour limiter le couplage dans la même couche
- correction du log HTMLcanvas dans Vitest
=> Ajouter un ou des porteurs UI

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(avec-menu)/layout.tsx, src/components/Action/AjouterDesBeneficiaires.test.tsx, src/components/Action/AjouterDesMembres.tsx, src/components/Action/AjouterUneAction.tsx, src/components/Action/FormulaireAction.tsx, src/components/Action/ModifierUneAction.tsx, src/components/Gouvernance/Comitologie/FormulaireComite.tsx, src/components/Gouvernance/Gouvernance.module.css, src/components/Gouvernance/Resume.tsx, src/components/TableauDeBord/TableauDeBord.tsx, src/components/shared/TextArea/TextArea.tsx
Correspond à tous les tickets où il y a ma tête dans la colonne "retour de tests"
=> Corrections mineures d'UI

src/components/Action/FormulaireAction.tsx, src/components/shared/Tag/Tag.tsx
=> Factorisation de Tag

prisma/migrations/20250303104850_corrections_nommage_snake_case/migration.sql, prisma/migrations/20250303110936_association_des_porteurs_aux_feuilles_de_route/migration.sql, prisma/schema.prisma, seeds/fne/schema.prisma, seeds/gouvernance.ts, seeds/utilisateur.ts
=> Correspondance feuille de route membre porteur

src/app/(connecte)/(avec-menu)/(default)/aidants-et-mediateurs/page.tsx, src/app/(connecte)/(avec-menu)/(default)/export-de-donnees/page.tsx, src/app/(connecte)/(avec-menu)/(default)/lieux-inclusion/page.tsx, src/app/(connecte)/(avec-menu)/(default)/rapports/page.tsx, src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(avec-menu)/beneficiaires/page.tsx, src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(avec-menu)/financements/page.tsx, src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(sans-menu)/feuille-de-route/[uidFeuilleDeRoute]/action/[uidAction]/page.tsx, src/app/(deconnecte)/auth-error/page.tsx, src/app/not-found.tsx, src/components/Accessibilite/Accessibilite.tsx, src/components/Action/FormulaireAction.tsx, src/components/Connexion/Connexion.tsx, src/components/FeuilleDeRoute/FeuilleDeRoute.tsx, src/components/FeuillesDeRoute/FeuillesDeRoute.tsx, src/components/GestionMembresGouvernance/GestionMembres.tsx, src/components/Gouvernance/Gouvernance.tsx, src/components/MentionsLegales/MentionsLegales.tsx, src/components/MesInformationsPersonnelles/MesInformationsPersonnelles.tsx, src/components/MesParametres/MesParametres.tsx, src/components/MesUtilisateurs/MesUtilisateurs.tsx, src/components/TableauDeBord/TableauDeBord.tsx, src/components/shared/PageTitle/PageTitle.tsx
=> Centraliser les titres h1

README.md, prisma/migrations/20250306150406_fix_datatype_add_columns/migration.sql, prisma/schema.prisma, seeds/gouvernance.ts, src/gateways/PrismaMembreRepository.test.ts, src/gateways/testHelper.ts
=> Fix : Add columns - Fix Datatype

src/gateways/PrismaGouvernanceLoader.test.ts, src/gateways/PrismaGouvernanceLoader.ts
=> Le nombre de membres affiché sur la gouvernance ne doit contenir que les membres confirmés

src/components/Action/Action.test.tsx, src/components/Action/DemanderUneSubvention.test.tsx, src/components/Action/DemanderUneSubvention.tsx, src/components/Action/FormulaireAction.tsx, src/components/MesInformationsPersonnelles/SupprimerMonCompte.module.css, src/components/MesInformationsPersonnelles/SupprimerMonCompte.tsx, src/global.css, src/presenters/actionPresenter.ts, src/presenters/testHelper.ts, src/shared/testHelper.ts
=> test(formulaire action gouvernance): drawer de demande de subvention

src/components/Action/AjouterDesBesoins.tsx, src/components/Action/AjouterDesMembres.tsx, src/components/Action/AjouterUnCoFinancement.tsx, src/components/Action/DemanderUneSubvention.tsx, src/components/Action/FormulaireAction.tsx, src/components/FeuilleDeRoute/FeuilleDeRoute.tsx, src/components/FeuilleDeRoute/ModifierUneFeuilleDeRoute.tsx, src/components/FeuillesDeRoute/FormulaireFeuilleDeRoute.tsx, src/components/GestionMembresGouvernance/AjouterUnMembre.tsx, src/components/MesUtilisateurs/FiltrerParRoles.tsx, src/components/MesUtilisateurs/InviterUnUtilisateur.tsx, src/components/shared/Checkbox/Checkbox.tsx, src/components/shared/Radio/RadioGroup.tsx, src/components/shared/Select/Select.tsx, src/components/transverse/EnTete/MenuUtilisateur/SelecteurRole/SelecteurRole.tsx, src/presenters/actionPresenter.ts, src/presenters/feuilleDeRoutePresenter.ts, src/presenters/feuillesDeRoutePresenter.ts, src/presenters/shared/labelValue.ts, src/presenters/testHelper.ts
=> refactor(Select): généralisation du composant Select

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(avec-menu)/feuilles-de-route/page.tsx, src/components/FeuillesDeRoute/AjouterUneFeuilleDeRoute.test.tsx, src/components/FeuillesDeRoute/DetailAction.test.tsx, src/components/FeuillesDeRoute/DetailAction.tsx, src/components/FeuillesDeRoute/FeuillesDeRoute.module.css, src/components/FeuillesDeRoute/FeuillesDeRoute.test.tsx, src/components/FeuillesDeRoute/ResumeAction.tsx, src/components/FeuillesDeRoute/ResumeFeuilleDeRoute.tsx, src/presenters/feuillesDeRoutePresenter.ts, src/presenters/shared/action.ts, src/use-cases/queries/RecupererLesFeuillesDeRoute.test.ts, src/use-cases/testHelper.ts
=> feat(feuilles de route): connexion des données aux écrans

src/components/FeuillesDeRoute/DetailAction.test.tsx, src/components/FeuillesDeRoute/DetailAction.tsx, src/components/FeuillesDeRoute/FeuillesDeRoute.module.css, src/components/FeuillesDeRoute/FeuillesDeRoute.tsx, src/components/FeuillesDeRoute/ResumeAction.tsx, src/gateways/PrismaLesFeuillesDeRouteLoader.ts, src/gateways/testHelper.ts, src/use-cases/queries/RecupererLesFeuillesDeRoute.test.ts, src/use-cases/queries/RecupererLesFeuillesDeRoute.ts, src/use-cases/testHelper.ts
=> fix(aperçu feuilles de route): calcul correct des montants

src/domain/FeuilleDeRoute.ts, src/use-cases/commands/ModifierUneNoteDeContextualisation.test.ts, src/use-cases/commands/ModifierUneNoteDeContextualisation.ts, src/use-cases/commands/shared/FeuilleDeRouteRepository.ts
=> Feat(note de contextualisation):  ajout du use cases & domain

src/app/api/actions/ajouterUneNoteDeContexteAction.ts, src/app/api/actions/ajouterUneNoteDeContextualisationAction.test.ts, src/app/api/actions/ajouterUneNoteDeContextualisationAction.ts, src/components/FeuilleDeRoute/AjouterUneNoteDeContextualisation.tsx, src/components/FeuilleDeRoute/FeuilleDeRoute.tsx, src/domain/FeuilleDeRoute.ts, src/use-cases/commands/AjouterUneNoteDeContextualisation.test.ts, src/use-cases/commands/AjouterUneNoteDeContextualisation.ts
#
des fichiers étaient restés en staging. 
=> configuration du yarn check pour qu'il vérifie sur les fichiers en staging
- [ X] Relire le code
- [- ] Relire le ticket
- [ -] [Relire les critères d'acceptation](https://github.com/anct-cnum/suite-gestionnaire-numerique/discussions/252)
- [ -] Vérifier le coverage
- [ -] Recetter l'application
- [ -] Ajouter des variables d'environnement sur la production au besoin
- [- ] Vérifier l'accessibilité avec a11y.css, WAVE, Axe, headingMap
- [- ] Naviguer au clavier
- [- ] Vérifier le constraste en mode sombre
=> 530 ajout de la note de contextualisation - Ajout de ifchier

src/app/api/actions/ajouterUneNoteDeContextualisationAction.test.ts, src/app/api/actions/supprimerUneNoteDeContextualisationAction.test.ts, src/app/api/actions/supprimerUneNoteDeContextualisationAction.ts, src/components/FeuilleDeRoute/ModifierUneNoteDeContextualisation.tsx, src/domain/FeuilleDeRoute.ts, src/gateways/PrismaFeuilleDeRouteRepository.test.ts, src/gateways/PrismaFeuilleDeRouteRepository.ts, src/use-cases/commands/SupprimerUneNoteDeContextextualisation.ts, src/use-cases/commands/SupprimerUneNoteDeContextualisation.test.ts
=> Feat: effacer une note de contextualisation 

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(sans-menu)/feuille-de-route/[uidFeuilleDeRoute]/action/ajouter/page.tsx, src/components/Action/Action.test.tsx, src/components/Action/AjouterDesBesoins.tsx, src/components/Action/DemanderUneSubvention.tsx, src/components/Action/FormulaireAction.tsx, src/presenters/actionPresenter.ts, src/presenters/testHelper.ts, src/use-cases/queries/RecupererUneAction.ts, yarn.lock
=> Feat: Ajouter un besoin sur une action : connecter les données

src/app/api/actions/inviterUnUtilisateurAction.test.ts, src/components/Action/Action.test.tsx, src/components/Action/AjouterDesBeneficiaires.test.tsx, src/components/Action/AjouterDesMembres.tsx, src/components/Action/AjouterDesPorteurs.test.tsx, src/components/Action/FormulaireAction.tsx, src/components/MesUtilisateurs/FiltrerMesUtilisateurs.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/shared/Pagination/Pagination.test.tsx, src/components/shared/Tag/Tag.tsx, src/presenters/actionPresenter.ts, src/presenters/gouvernancePresenter.ts, src/presenters/shared/PorteurPotentiel.ts, src/presenters/testHelper.ts
=> Ajouter porteurs nouvelle action

src/components/Action/AjouterDesBeneficiaires.test.tsx, src/components/Action/AjouterDesMembres.tsx, src/components/Action/FormulaireAction.tsx, src/presenters/shared/PorteurPotentiel.ts
- [- ] Vérifier l'accessibilité avec a11y.css, WAVE, Axe, headingMap
- [- ] Naviguer au clavier
- [- ] Vérifier le constraste en mode sombre
- [- ] Lancer les tests de mutation
=> Ajout des bénéficiaires

src/gateways/PrismaUneFeuilleDeRouteLoader.test.ts, src/gateways/PrismaUneFeuilleDeRouteLoader.ts
=> Feat(Feuille de route): date de modification + nom & prénom  (débouchonnement)

src/components/Action/Action.test.tsx, src/components/Action/AjouterDesBesoins.test.tsx, src/components/Action/AjouterDesBesoins.tsx, src/components/Action/FormulaireAction.tsx, src/presenters/actionPresenter.ts
=> Retour Ajouter le(s) besoin(s)

src/components/Action/Action.test.tsx, src/components/Action/AjouterDesMembres.tsx, src/components/Action/FormulaireAction.tsx, src/components/shared/Badge/Badge.tsx, src/components/shared/Tag/Tag.tsx
=> 532 retour ajout porteur et beneficiaire

src/components/FeuillesDeRoute/DetailAction.test.tsx, src/components/FeuillesDeRoute/DetailAction.tsx, src/components/FeuillesDeRoute/FeuillesDeRoute.module.css, src/gateways/PrismaUneFeuilleDeRouteLoader.test.ts, src/gateways/PrismaUneFeuilleDeRouteLoader.ts, src/presenters/feuillesDeRoutePresenter.ts
=> 450 fix affichage drawer details action

src/app/api/actions/ajouterUneActionAction.ts, src/gateways/PrismaLesFeuillesDeRouteLoader.test.ts, src/gateways/PrismaMesMembresLoader.test.ts, src/gateways/PrismaMesMembresLoader.ts, src/gateways/shared/MembresGouvernance.ts, src/presenters/actionPresenter.ts, src/presenters/testHelper.ts, src/use-cases/commands/AjouterUneAction.test.ts, src/use-cases/commands/AjouterUneAction.ts, src/use-cases/queries/RecupererUneAction.ts
=> Fix besoins

src/components/GestionMembresGouvernance/GestionMembres.test.tsx, src/components/GestionMembresGouvernance/GestionMembres.tsx
=> cacher le bouton export des membres

src/components/TableauDeBord/TableauDeBord.module.css, src/components/TableauDeBord/TableauDeBord.tsx
=> cacher les sections du tableau de prefecture

src/components/GestionMembresGouvernance/GestionMembres.test.tsx, src/components/GestionMembresGouvernance/GestionMembres.tsx, src/global.css
=> coche la suppression des membres de la gouvernance

src/components/Action/FormulaireAction.tsx, src/components/Action/TemporaliteAction.tsx
=> modifier la temporalitée

src/components/MesParametres/MesParametres.module.css, src/components/MesParametres/MesParametres.tsx
=> cacher la section Communication et notifications

src/components/Gouvernance/Gouvernance.test.tsx, src/presenters/gouvernancePresenter.ts
=> suppression du nombre de membres dans la section membre du comitÃe

src/app/(connecte)/(avec-menu)/gouvernance/[codeDepartement]/(sans-menu)/feuille-de-route/[uidFeuilleDeRoute]/action/ajouter/page.tsx
=> enleve le bandeau donnees fictives pour ajouter une action

src/components/Gouvernance/Gouvernance.test.tsx, src/presenters/gouvernancePresenter.ts
=> changer la redirection des feuilles de routes

src/components/FeuilleDeRoute/FeuilleDeRoute.tsx, src/components/FeuillesDeRoute/ResumeAction.tsx
=> correction visuel

src/components/Membre/Membre.tsx
=> correction visuel de la page en construction pour le detail d'un membre

src/gateways/PrismaUneFeuilleDeRouteLoader.test.ts, src/gateways/PrismaUneFeuilleDeRouteLoader.ts, src/presenters/actionPresenter.ts, src/presenters/feuilleDeRoutePresenter.ts, src/presenters/shared/besoins.ts, src/presenters/testHelper.ts, src/use-cases/queries/RecupererUneAction.ts, src/use-cases/queries/RecupererUneFeuilleDeRoute.ts, src/use-cases/queries/shared/ActionReadModel.ts, src/use-cases/testHelper.ts
=> 651 : orthographier correctement les libelles des besoins

src/app/(connecte)/layout.tsx, src/app/(deconnecte)/deconnexion/page.tsx, src/app/(deconnecte)/layout.tsx, src/gateways/NextAuthAuthentificationGateway.ts, src/gateways/PrismaUtilisateurLoader.test.ts, src/gateways/PrismaUtilisateurLoader.ts, src/middleware.ts
=> #681 : permet de reinisialiser les identifiant proconnect en base

src/components/shared/Carte/Carte.tsx, src/presenters/tableauDeBord/financementPresenter.ts
=> Retour UI simple

src/app/(connecte)/(avec-menu)/(default)/tableau-de-bord/page.tsx, src/components/TableauDeBord/Gouvernance/Gouvernance.tsx, src/components/TableauDeBord/TableauDeBord.test.tsx, src/components/TableauDeBord/TableauDeBord.tsx, src/gateways/PrismaGouvernanceTableauDeBordLoader.ts, src/presenters/tableauDeBord/gouvernancePresenter.ts, src/presenters/tableauDeBord/tableauDeBordPresenter.ts, src/use-cases/queries/RecupererTableauDeBordGouvernance.ts
=> 536 tableau de bord gouvernances

prisma/migrations/20250711142414_suppression_date_membres/migration.sql, prisma/schema.prisma, src/app/api/actions/supprimerUnMembreOuCandidatAction.ts, src/components/GestionMembresGouvernance/GestionMembres.tsx, src/components/shared/ClientContext.tsx, src/components/shared/Menu/Menu.tsx, src/components/testHelper.tsx, src/domain/Membre.ts, src/domain/MembreCandidat.ts, src/domain/MembreConfirme.ts, src/domain/MembreSupprimer.ts, src/domain/shared/Model.ts, src/gateways/PrismaMembreRepository.test.ts, src/gateways/PrismaMembreRepository.ts, src/presenters/membresPresenter.ts, src/use-cases/CommandHandler.ts, src/use-cases/commands/SupprimerUnMembreOuCandidat.ts, src/use-cases/queries/RecupererMesMembres.ts
=> suppression membre et candidat

src/components/shared/Carte/Carte.tsx
=> 535 : enlever l'animation à l'ouverture de la carte

src/components/GestionMembresGouvernance/GestionMembres.tsx, src/components/shared/Table/Table.tsx
=> fix visuel tableau

src/app/(connecte)/(avec-menu)/(default)/tableau-de-bord/page.tsx, src/components/TableauDeBord/FeuillesDeRouteDeposees.tsx, src/components/TableauDeBord/GouvernancesTerritoriales.tsx, src/components/TableauDeBord/TableauDeBordAdmin.tsx, src/components/shared/Dot/Dot.module.css, src/gateways/tableauDeBord/PrismaFeuillesDeRouteDeposeesLoader.ts, src/gateways/tableauDeBord/PrismaGouvernancesTerritorialesLoader.ts, src/presenters/tableauDeBord/feuillesDeRouteDeposeesPresenter.ts, src/presenters/tableauDeBord/gouvernancesTerritorialesPresenter.ts, src/use-cases/queries/RecuperGouvernancesTerritoriales.ts, src/use-cases/queries/RecupererFeuillesDeRouteDeposees.ts
=> Ajout des 2 premiers graphiques du dashboard admin : gouvernances et FDR

src/components/Gouvernance/Gouvernance.tsx, src/components/TableauDeBord/FeuillesDeRouteDeposees.tsx, src/components/TableauDeBord/GouvernancesTerritoriales.tsx, src/components/TableauDeBord/TableauDeBordAdmin.tsx, src/gateways/tableauDeBord/PrismaGouvernancesTerritorialesLoader.ts, src/presenters/tableauDeBord/feuillesDeRouteDeposeesPresenter.ts
=> 750 : retour sur les graphiques.

package.json, src/components/TableauDeBord/FeuillesDeRouteDeposees.tsx, src/components/TableauDeBord/GouvernancesTerritoriales.tsx, src/components/TableauDeBord/TableauDeBordAdmin.tsx, yarn.lock
=> 750 : ajout du bouton télécharger sur les 2 charts

src/components/MesUtilisateurs/InviterUnUtilisateur.test.tsx, src/components/MesUtilisateurs/MesUtilisateurs.test.tsx, src/components/transverse/MenuLateral/MenuLateral.test.tsx, src/components/transverse/MenuLateral/MenuLateral.tsx, src/gateways/tableauDeBord/PrismaIndicesDeFragiliteLoader.ts, src/presenters/sessionUtilisateurPresenter.test.ts, src/presenters/sessionUtilisateurPresenter.ts, src/presenters/testHelper.ts
=> 750 : ajout du menu latéral pour l'adminstrateur de dispositif

src/app/(connecte)/(avec-menu)/(default)/tableau-de-bord/page.tsx, src/components/TableauDeBord/Financements.tsx, src/gateways/tableauDeBord/PrismaFinancementsLoader.ts, src/presenters/shared/number.ts, src/presenters/tableauDeBord/financementPresenter.ts, src/use-cases/queries/RecuperFinancements.ts
=> 759: TDB admin. Adaptation financements au contexte admin

src/components/TableauDeBord/Beneficiaires.tsx, src/presenters/tableauDeBord/tableauDeBordPresenter.ts
=> 760 : liens teasing et typo

src/components/AidantsMediateurs/AccompagnementsEtMediateurs.tsx, src/components/AidantsMediateurs/AidantsMediateurs.tsx, src/components/shared/Metric/Metric.tsx, src/gateways/aidantsMedIateurs/PrismaAccompagnementsEtMediateursLoader.ts, src/gateways/aidantsMedIateurs/PrismaNiveauDeFormationLoader.ts, src/use-cases/queries/RecupererNiveauDeFormation.ts
=> 735 statistiques aidants mediateurs

src/app/(connecte)/(avec-menu)/(default)/liste-aidants-mediateurs/page.tsx, src/components/AidantsMediateurs/AidantsMediateurs.tsx, src/components/Gouvernances/GouvernancesInfos.tsx, src/components/ListeAidantsMediateurs/ListeAidantsMediateurInfos.tsx, src/components/ListeAidantsMediateurs/ListeAidantsMediateurs.tsx, src/components/shared/AlerteConstruction/AlerteConstruction.tsx, src/gateways/PrismaListeAidantsMediateursLoader.ts, src/presenters/listeAidantsMediateursPresenter.ts, src/shared/textFormatting.tsx, src/use-cases/queries/RecupererListeAidantsMediateurs.ts
=> ajout du front pour la liste aidant et mediatieurs

knip.json, src/components/ListeAidantsMediateurs/ListeAidantsMediateurs.tsx, src/gateways/PrismaListeAidantsMediateursLoader.ts
=> correction request tableau aidant connect

create_vue_personne_typee.sql, prisma/migrations/20250828071256_creation_vue_personne_enrichie/migration.sql, prisma/schema.prisma, src/gateways/PrismaListeAidantsMediateursLoader.ts, src/gateways/aidantsMedIateurs/PrismaAccompagnementsEtMediateursLoader.ts, src/gateways/aidantsMedIateurs/PrismaNiveauDeFormationLoader.ts, src/gateways/tableauDeBord/PrismaAccompagnementsRealisesLoader.ts, src/gateways/tableauDeBord/PrismaMediateursEtAidantsLoader.ts, src/presenters/tableauDeBord/accompagnementsEtMediateursPresenter.ts
=> Dataspace personne creation vue bdd

prisma/migrations/20250903123748_ajout_cles_primaires_tables_association/migration.sql, prisma/schema.prisma
=> Ajout de PK sur 3 tables d'assocations.

src/components/AidantDetails/AidantDetails.tsx, src/components/AidantDetails/AidantDetailsLieuxActivite.tsx, src/gateways/AidantDetailsLoader.ts, src/presenters/AidantDetailsPresenter.ts, src/stories/Components/AidantDetails/AidantDetailsTestData.ts, src/use-cases/queries/RecupererAidantDetails.ts
=> ajout des lieux d activité

src/components/ListeLieuxInclusion/ListeLieuxInclusion.tsx, src/components/ListeLieuxInclusion/ListeLieuxInclusionInfo.tsx, src/gateways/PrismaLieuxInclusionNumeriqueLoader.ts, src/gateways/PrismaListeLieuxInclusionLoader.ts, src/gateways/tableauDeBord/PrismaLieuxInclusionNumeriqueLoader.ts, src/presenters/listeLieuxInclusionPresenter.ts, src/use-cases/queries/RecupererLieuxInclusion.ts
=> 853 discussion autour des lieux

.env, prisma/migrations/20250619151605_2_dataspace_integration/migration.sql, prisma/migrations/20250828071256_creation_vue_personne_enrichie/migration.sql, prisma/schema.prisma
Le schéma du dataspace uniformise le lien entre une personne et la structure.
Prise en compte de cela. On passe par la table d'asso  personne_affection de manière systématique.
Seule la vue personne_enrichie est impactée. Le reste est du mapping automatique
=> 877 maj du dataspace fusion des structures entre les aidant et la coop

src/app/(connecte)/(sans-menu)/liste-lieux-inclusion/page.tsx, src/app/api/export/lieux-inclusion-csv/route.ts, src/components/ListeLieuxInclusion/ListeLieuxInclusion.tsx, src/components/ListeLieuxInclusion/ListeLieuxInclusionFiltre.tsx, src/gateways/PrismaListeLieuxInclusionLoader.ts, src/shared/filtresLieuxInclusionUtils.ts, src/shared/prismaQueryHelpers.ts, src/use-cases/queries/RecupererLieuxInclusion.ts
=> 884 filtre sur les lieux dinclusion
